include: package:netglade_analysis/lints.yaml

dart_code_metrics:
  extends:
    - package:netglade_analysis/dcm.yaml
  pubspec-rules:
    prefer-publish-to-none: false
    # TODO: Support analyzer same way as json_serializable https://github.com/google/json_serializable.dart/pull/1333
    prefer-caret-version-syntax: false
